### ISSUE TITLE
[DOCS] Explicitly require @remix-run/server-runtime?

### ISSUE THREAD

**Issue by TheRealFlyingCoder** [sergiodxa/remix-auth#212]
### Describe the bug

Just wondering whether the docs should be including the addition of installing `@remix-run/server-runtime` as a dependency?

It's set as a peer and only works because @remix-run/node requires it as a dependency, but when you switch up to yarn berry it'll eventually error as the resolution is incorrect

### Your Example Website or App

-

### Steps to Reproduce the Bug or Issue

-

### Expected behavior

-

### Platform

-

**Comment by TheRealFlyingCoder** [comment]
Ignore this, even manually installing doesn't work in Berry, had to add this:

```
packageExtensions:
    remix-auth@*:
        dependencies:
            '@remix-run/server-runtime': '*'
    remix-auth-oauth2@*:
        dependencies:
            '@remix-run/server-runtime': '*'
```
